### ISSUE TITLE
A preset that has a (peer) dependency on a package in a private repo

### ISSUE THREAD

**Issue by faassen** [alvis/presetter#9]
I have a preset that has a peer dependency on a package that's published on a private github repo. When I use `presetter use` it takes a long time and then finally crashes complaining it cannot find this dependency on `registry.npmjs.org` which makes sense as it isn't there.

I tried to put this configuration in a `.npmrc` in the module that wants to use the preset, but it didn't work. (I'd prefer to have this .npmrc to be *part* of the preset anyway).

I tried passing through this configuration through the `npm_package_repository_url` environment variable but it wasn't successful.

Perhaps there's a better way to do this I'm not aware of, or perhaps presetter needs support for this in some way.

**Comment by alvis** [comment]
I'm guessing if the private registry setting is missing. 

In line with `npm`, when using a private registry you have to use
```
npx --registry <path to a private registry> presetter use <a preset package in your private registry>
```

Would you mind sharing with my the exact command you used above?

**Comment by alvis** [comment]
@faassen `node 14` and private registry supports have been added in v3.1.
It should support all of your use cases now :)
